/* eslint-disable no-undef */
import type { Metadata, Viewport } from "next";

import "./globals.css";

// import { GoogleTagManager } from "@next/third-parties/google";
import SessionProvider from "./context/session";
import ReactQueryProvider from "./context/rquery";
import Layout from "@/app/components/layouts/primary";
// import montserrat from "@/font";
import { Montserrat } from "next/font/google";
const font = Montserrat({
  preload: false,
});

export const metadata: Metadata = {
  title: "Get Right Property",
  description: "Generated by Get Right Property",
};
export default function RootLayout(params: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="lazyOnload"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9243707404617437"
          crossOrigin="anonymous"
        />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicons/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicons/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicons/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicons/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicons/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicons/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicons/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="google-adsense-account" content="ca-pub-9243707404617437" />
      </head>

      {process.env.NODE_ENV !== "development" && (
        <Script
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-T7W6VL9F');`,
          }}
        />
      )}

      <body className={font.className}>
        {/* <MantineProvider theme={MantineTheme}> */}
        <main>
          <SessionProvider>
            <ReactQueryProvider>
              {/* <JotaiProvider> */}
              {/* <Header /> */}
              <Layout>{params.children}</Layout>
              {/* <Footer /> */}
              {/* </JotaiProvider> */}
            </ReactQueryProvider>
          </SessionProvider>
        </main>
        {/* <Footer /> */}
        {/* </MantineProvider> */}
      </body>
    </html>
  );
}
import Script from "next/script";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: "#ffffff",
};
